### PR TITLE
Fixes a bug (ArgumentException in TimeZoneDefinition)

### PR DESCRIPTION
**Pull request by aersamkull**
I had to add this "ContainsKey" Check in order to make the EWS Api work with some Appointments.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aersamkull__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@aersamkull__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by aersamkull** [comment]
Yes, it is very likely to hide a server-side issue, but this is something I cannot fix :) So I think we might should handle it here as well to be more stable. The Timezone was a Japanese One, Tokyo Standard Time I think. Do you need more information?

Sorry, the try-catch block was not intended, it was just necessary to run the project as there was resource file missing.

**Comment by dclaux** [comment]
It would really be helpful to have the full details of the time zone that causes the issue, if you have it. You can turn tracing on by setting TraceEnabled to true on th ExchangeService instance; that will output the XML returned by the server, which will contain the full definition of the problematic time zone. I do understand that fixing the API is the best you have given you can't fix the server, and I agree it could make sense, but if the API fix makes up for an incorrect time zone it can actually get pretty ugly.

**Comment by aersamkull** [comment]
Maybe it is worth mentioning that Outlook Online was used. The timezone is really special, but someone really did add two different time zones...
Here is the (censored :) ) xml.:
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo MajorVersion="15" MinorVersion="1" MajorBuildNumber="87" MinorBuildNumber="20" Version="V2_34" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <m:GetItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:GetItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items>
            <t:CalendarItem>
              <t:ItemId Id="AAMkADg0ZmQ1Yzk5LTBkNjktNGY1Yi1hMjA3LTNlODBiOTIyOGM5MAFRAAgI0Scd8cmAAEYAAAAAYIsV97q6E0arn8qWnWou6gcAHRvV2fVW3kWHIjw0U2Un7QAAAAABDgAAHRvV2fVW3kWHIjw0U2Un7QAARr3DJgAAEA==" ChangeKey="DwAAABYAAAAdG9XZ9VbeRYciPDRTZSftAACUnou6"/>
              <t:ParentFolderId Id="AAMkADg0ZmQ1Yzk5LTBkNjktNGY1Yi1hMjA3LTNlODBiOTIyOGM5MAAuAAAAAABgixX3uroTRqufypadai7qAQAdG9XZ9VbeRYciPDRTZSftAAAAAAEOAAA=" ChangeKey="AQAAAA=="/>
              <t:ItemClass>IPM.Appointment.Occurrence</t:ItemClass>
              <t:Subject>company1 / company2 asdfljiwelf review</t:Subject>
              <t:Sensitivity>Normal</t:Sensitivity>
              <t:Body BodyType="HTML">
              
              </t:Body>
              <t:DateTimeReceived>2014-10-23T15:03:45Z</t:DateTimeReceived>
              <t:Size>60546</t:Size>
              <t:Importance>Normal</t:Importance>
              <t:IsSubmitted>false</t:IsSubmitted>
              <t:IsDraft>false</t:IsDraft>
              <t:IsFromMe>false</t:IsFromMe>
              <t:IsResend>false</t:IsResend>
              <t:IsUnmodified>false</t:IsUnmodified>
              <t:DateTimeSent>2014-10-23T15:03:45Z</t:DateTimeSent>
              <t:DateTimeCreated>2014-10-23T15:03:45Z</t:DateTimeCreated>
              <t:ResponseObjects>
                <t:AcceptItem/>
                <t:TentativelyAcceptItem/>
                <t:DeclineItem/>
                <t:ReplyToItem/>
                <t:ReplyAllToItem/>
                <t:ForwardItem/>
              </t:ResponseObjects>
              <t:ReminderDueBy>2015-03-18T08:00:00Z</t:ReminderDueBy>
              <t:ReminderIsSet>true</t:ReminderIsSet>
              <t:ReminderMinutesBeforeStart>15</t:ReminderMinutesBeforeStart>
              <t:DisplayCc>a, b; c, d</t:DisplayCc>
              <t:DisplayTo>a; b; c; d; e</t:DisplayTo>
              <t:HasAttachments>false</t:HasAttachments>
              <t:Culture>en-US</t:Culture>
              <t:EffectiveRights>
                <t:CreateAssociated>false</t:CreateAssociated>
                <t:CreateContents>false</t:CreateContents>
                <t:CreateHierarchy>false</t:CreateHierarchy>
                <t:Delete>true</t:Delete>
                <t:Modify>true</t:Modify>
                <t:Read>true</t:Read>
                <t:ViewPrivateItems>true</t:ViewPrivateItems>
              </t:EffectiveRights>
              <t:LastModifiedName>tool1 company1</t:LastModifiedName>
              <t:LastModifiedTime>2015-02-18T07:59:31Z</t:LastModifiedTime>
              <t:IsAssociated>false</t:IsAssociated>
              <t:WebClientReadFormQueryString>?ItemID=AAMkADg0ZmQ1Yzk5LTBkNjktNGY1Yi1hMjA3LTNlODBiOTIyOGM5MAFRAAgI0Scd8cmAAEYAAAAAYIsV97q6E0arn8qWnWou6gcAHRvV2fVW3kWHIjw0U2Un7QAAAAABDgAAHRvV2fVW3kWHIjw0U2Un7QAARr3DJgAAEA%3D%3D&amp;exvsurl=1&amp;viewmodel=ReadMessageItem</t:WebClientReadFormQueryString>
              <t:ConversationId Id="AAQkADg0ZmQ1Yzk5LTBkNjktNGY1Yi1hMjA3LTNlODBiOTIyOGM5MAAQAAB4SwGiIUPkp8o+y1yLhic="/>
              <t:UID>040000008200E00074C5B7101A82E00800000000900FA2D2DBE4CE0100000000000000001000000067964FB18A90CC4798D89DBE1A823BDF</t:UID>
              <t:RecurrenceId>2014-04-16T08:00:00Z</t:RecurrenceId>
              <t:DateTimeStamp>2015-02-18T07:59:25Z</t:DateTimeStamp>
              <t:Start>2014-04-16T08:00:00Z</t:Start>
              <t:End>2014-04-16T09:00:00Z</t:End>
              <t:OriginalStart>2014-04-16T08:00:00Z</t:OriginalStart>
              <t:IsAllDayEvent>false</t:IsAllDayEvent>
              <t:LegacyFreeBusyStatus>Tentative</t:LegacyFreeBusyStatus>
              <t:Location>company1 </t:Location>
              <t:IsMeeting>true</t:IsMeeting>
              <t:IsCancelled>false</t:IsCancelled>
              <t:IsRecurring>true</t:IsRecurring>
              <t:MeetingRequestWasSent>false</t:MeetingRequestWasSent>
              <t:IsResponseRequested>true</t:IsResponseRequested>
              <t:CalendarItemType>Occurrence</t:CalendarItemType>
              <t:MyResponseType>Tentative</t:MyResponseType>
              <t:Organizer>
                <t:Mailbox>
                  <t:Name>Nsdf</t:Name>
                  <t:EmailAddress>neiom</t:EmailAddress>
                  <t:RoutingType>SMTP</t:RoutingType>
                  <t:MailboxType>Mailbox</t:MailboxType>
                </t:Mailbox>
              </t:Organizer>
              <t:RequiredAttendees>
                <t:Attendee>
                  <t:Mailbox>
                    <t:Name>Nasdf</t:Name>
                    <t:EmailAddress>nasdfm</t:EmailAddress>
                    <t:RoutingType>SMTP</t:RoutingType>
                  </t:Mailbox>
                  <t:ResponseType>Unknown</t:ResponseType>
                </t:Attendee>
                <t:Attendee>
                  <t:Mailbox>
                    <t:Name>Pasdfr</t:Name>
                    <t:EmailAddress>asdf</t:EmailAddress>
                    <t:RoutingType>SMTP</t:RoutingType>
                  </t:Mailbox>
                  <t:ResponseType>Unknown</t:ResponseType>
                </t:Attendee>
                <t:Attendee>
                  <t:Mailbox>
                    <t:Name>tool1 company1 </t:Name>
                    <t:EmailAddress>asdf</t:EmailAddress>
                    <t:RoutingType>SMTP</t:RoutingType>
                  </t:Mailbox>
                  <t:ResponseType>Unknown</t:ResponseType>
                </t:Attendee>
                <t:Attendee>
                  <t:Mailbox>
                    <t:Name>asdf</t:Name>
                    <t:EmailAddress>asdf</t:EmailAddress>
                    <t:RoutingType>SMTP</t:RoutingType>
                  </t:Mailbox>
                  <t:ResponseType>Unknown</t:ResponseType>
                </t:Attendee>
                <t:Attendee>
                  <t:Mailbox>
                    <t:Name>asdf</t:Name>
                    <t:EmailAddress>asdf</t:EmailAddress>
                    <t:RoutingType>UNKNOWN</t:RoutingType>
                  </t:Mailbox>
                  <t:ResponseType>Unknown</t:ResponseType>
                </t:Attendee>
              </t:RequiredAttendees>
              <t:OptionalAttendees>
                <t:Attendee>
                  <t:Mailbox>
                    <t:Name>asdf</t:Name>
                    <t:EmailAddress>asdf</t:EmailAddress>
                    <t:RoutingType>SMTP</t:RoutingType>
                  </t:Mailbox>
                  <t:ResponseType>Unknown</t:ResponseType>
                </t:Attendee>
                <t:Attendee>
                  <t:Mailbox>
                    <t:Name>asdf</t:Name>
                    <t:EmailAddress>sdf</t:EmailAddress>
                    <t:RoutingType>SMTP</t:RoutingType>
                  </t:Mailbox>
                  <t:ResponseType>Unknown</t:ResponseType>
                </t:Attendee>
              </t:OptionalAttendees>
              <t:Duration>PT1H</t:Duration>
              <t:TimeZone>(GMT+09:00) Osaka, Sapporo, Tokyo</t:TimeZone>
              <t:AppointmentSequenceNumber>21</t:AppointmentSequenceNumber>
              <t:AppointmentState>3</t:AppointmentState>
              <t:StartTimeZone Name="(UTC+09:00) Osaka, Sapporo, Tokyo" Id="Tokyo Standard Time">
                <t:Periods>
                  <t:Period Bias="-PT9H" Name="Standard" Id="trule:Microsoft/Registry/Tokyo Standard Time/1-Standard"/>
                </t:Periods>
                <t:TransitionsGroups>
                  <t:TransitionsGroup Id="0">
                    <t:Transition>
                      <t:To Kind="Period">trule:Microsoft/Registry/Tokyo Standard Time/1-Standard</t:To>
                    </t:Transition>
                  </t:TransitionsGroup>
                </t:TransitionsGroups>
                <t:Transitions>
                  <t:Transition>
                    <t:To Kind="Group">0</t:To>
                  </t:Transition>
                </t:Transitions>
              </t:StartTimeZone>
              <t:EndTimeZone Name="(UTC-05:00) Eastern Time (US &amp; Canada)" Id="Eastern Standard Time">
                <t:Periods>
                  <t:Period Bias="PT5H" Name="Standard" Id="trule:Microsoft/Registry/Eastern Standard Time/2006-Standard"/>
                  <t:Period Bias="PT4H" Name="Daylight" Id="trule:Microsoft/Registry/Eastern Standard Time/2006-Daylight"/>
                  <t:Period Bias="PT5H" Name="Standard" Id="trule:Microsoft/Registry/Eastern Standard Time/2007-Standard"/>
                  <t:Period Bias="PT4H" Name="Daylight" Id="trule:Microsoft/Registry/Eastern Standard Time/2007-Daylight"/>
                </t:Periods>
                <t:TransitionsGroups>
                  <t:TransitionsGroup Id="0">
                    <t:RecurringDayTransition>
                      <t:To Kind="Period">trule:Microsoft/Registry/Eastern Standard Time/2006-Daylight</t:To>
                      <t:TimeOffset>PT2H</t:TimeOffset>
                      <t:Month>4</t:Month>
                      <t:DayOfWeek>Sunday</t:DayOfWeek>
                      <t:Occurrence>1</t:Occurrence>
                    </t:RecurringDayTransition>
                    <t:RecurringDayTransition>
                      <t:To Kind="Period">trule:Microsoft/Registry/Eastern Standard Time/2006-Standard</t:To>
                      <t:TimeOffset>PT2H</t:TimeOffset>
                      <t:Month>10</t:Month>
                      <t:DayOfWeek>Sunday</t:DayOfWeek>
                      <t:Occurrence>-1</t:Occurrence>
                    </t:RecurringDayTransition>
                  </t:TransitionsGroup>
                  <t:TransitionsGroup Id="1">
                    <t:RecurringDayTransition>
                      <t:To Kind="Period">trule:Microsoft/Registry/Eastern Standard Time/2007-Daylight</t:To>
                      <t:TimeOffset>PT2H</t:TimeOffset>
                      <t:Month>3</t:Month>
                      <t:DayOfWeek>Sunday</t:DayOfWeek>
                      <t:Occurrence>2</t:Occurrence>
                    </t:RecurringDayTransition>
                    <t:RecurringDayTransition>
                      <t:To Kind="Period">trule:Microsoft/Registry/Eastern Standard Time/2007-Standard</t:To>
                      <t:TimeOffset>PT2H</t:TimeOffset>
                      <t:Month>11</t:Month>
                      <t:DayOfWeek>Sunday</t:DayOfWeek>
                      <t:Occurrence>1</t:Occurrence>
                    </t:RecurringDayTransition>
                  </t:TransitionsGroup>
                </t:TransitionsGroups>
                <t:Transitions>
                  <t:Transition>
                    <t:To Kind="Group">0</t:To>
                  </t:Transition>
                  <t:AbsoluteDateTransition>
                    <t:To Kind="Group">1</t:To>
                    <t:DateTime>2007-01-01T00:00:00</t:DateTime>
                  </t:AbsoluteDateTransition>
                </t:Transitions>
              </t:EndTimeZone>
              <t:ConferenceType>0</t:ConferenceType>
              <t:AllowNewTimeProposal>true</t:AllowNewTimeProposal>
              <t:NetShowUrl/>
            </t:CalendarItem>
          </m:Items>
        </m:GetItemResponseMessage>
      </m:ResponseMessages>
    </m:GetItemResponse>
  </s:Body>
</s:Envelope>
```

**Comment by dclaux** [comment]
Thank you, I'll take a look.

**Comment by dclaux** [comment]
I do not see any duplicate transition group or transition period ID in that time zone. Are you still able to repro the problem? Also, was it a one-off issue or is it something you can repro with multiple calendar items?

**Comment by aersamkull** [comment]
No, I can reproduce it only with this calendar item. But it seems to be more complicated then I thought, I need to have a look once I have time.

**Comment by dclaux** [comment]
Closing this pull request for now until we get more information about the issue.

**Pull request closed without merging**
