### PR TITLE
#51 Null check for empty workweek

### PR DESCRIPTION
**Pull request by LasseHynninen**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@LasseHynninen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by LasseHynninen** [comment]
No problem, better to match the overall style.

**Comment by azurecla** [comment]
Hi __@LasseHynninen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by dclaux** [comment]
Thanks for your contribution!

**Pull request merged**
