### PR TITLE
Fix #86: Add Serialization Constructors for Exceptions

### LINKED ISSUE #86: Exception classes do not have all constructors required for serialization
See CA1032 https://msdn.microsoft.com/en-us/library/ms182151.aspx

Without the constructor for (SerializationInfo, StreamingContext), you get exceptions when serializing, such as:

```
An exception of type 'System.ServiceModel.Dispatcher.NetDispatcherFaultException' occurred in MyLibrary.dll but was not handled in user code

Additional information: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://MyNamespace:FetchResult. The InnerException message was 'The constructor with parameters (SerializationInfo, StreamingContext) is not found in ISerializable type 'Microsoft.Exchange.WebServices.Data.ServiceRequestException'.'.
```

### PR DESCRIPTION
**Pull request by VasiliyZhushma**
Fix for issue #86. Added constructors and methods required
for serialization for exception classes. This is required to get
actual exceptions on client side of ditributed application.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@VasiliyZhushma__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@VasiliyZhushma__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by VasiliyZhushma** [comment]
Is the repository alive?

**Comment by poizan42** [comment]
Doesn't seems like there have been any activity by msft'ers since february. @davster @dclaux are there still anyone assigned internally to work on the EWS managed api?

**Pull request merged**
